### ISSUE TITLE
Issue in progress_bar.py

### ISSUE THREAD

**Issue by mohitthakur007** [jqug/microscopy-object-detection#2]
I tried to make tuberculosis python notebook work but I got stuck with this error
![Screenshot 2020-07-27 at 9 44 43 PM](https://user-images.githubusercontent.com/41528050/88565826-c0dfa780-d052-11ea-8722-e6e304154f5d.png)
![Screenshot 2020-07-27 at 9 45 05 PM](https://user-images.githubusercontent.com/41528050/88565866-cb9a3c80-d052-11ea-9203-002aaddfab9c.png)

Please help!

**Comment by rwakazooba** [comment]
Hi Mohit,

You did not mention what version of python you are running, I propose you run this with v2.7 this environment may save you the errors due to different versions of python or numpy....specifically with the parsing and casting of double to int.

Another way around [quick fix]this would be to use the int() function to cast line 30... for example the error you get arises from a float (decimal) being returned for _pct_place_ ; you could add something like `int(pct_place)` to cast the same back to an integer.

A better solution would be to run the code under the same python environment, so that you dont have to make those little fixes due to differences in versions.

Hope that helps.
Ezra.
